1.1 Creating a Vector

In [3]:
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
[2],
[3]])

print(vector_column)


[[1]
 [2]
 [3]]


1.2 Creating a Matrix

In [5]:
# Load library
import numpy as np
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


Discussion

In [ ]:
matrix_object = np.mat([[1, 2],
[1, 2],
[1, 2]])
matrix([[1, 2],
[1, 2],
[1, 2]])

1.3 Creating a Sparse Matrix



In [8]:
# Load libraries
import numpy as np
from scipy import sparse

# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [10]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# View larger sparse matrix
print(matrix_large_sparse)


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


1.4 Selecting Elements



In [13]:
# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
vector[2]

# Select second row, second column
matrix[1,1]


np.int64(5)

In [14]:
# Select all elements of a vector
vector[:]


array([1, 2, 3, 4, 5, 6])

In [15]:
# Select everything up to and including the third element
vector[:3]


array([1, 2, 3])

In [16]:
# Select the last element
vector[-1]


np.int64(6)

In [17]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# Select all rows and the second column
matrix[:,1:2]


array([[2],
       [5],
       [8]])

1.5 Describing a Matrix



In [19]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# View number of rows and columns
matrix.shape


(3, 4)

In [20]:
# View number of elements (rows * columns)
matrix.size


12

In [21]:
# View number of dimensions
matrix.ndim


2

1.6 Applying Operations to Elements



In [22]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [23]:
# Add 100 to all elements
matrix + 100


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

1.7 Finding the Maximum and Minimum Values



In [24]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum element
np.max(matrix)


np.int64(9)

In [25]:
# Return minimum element
np.min(matrix)


np.int64(1)

In [26]:
# Find maximum element in each column
np.max(matrix, axis=0)


array([7, 8, 9])

In [27]:
# Find maximum element in each row
np.max(matrix, axis=1)


array([3, 6, 9])

1.8 Calculating the Average, Variance, and Standard Deviation



In [29]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
np.mean(matrix)


np.float64(5.0)

In [28]:
# Return variance
np.var(matrix)


np.float64(6.666666666666667)

In [30]:
# Return standard deviation
np.std(matrix)


np.float64(2.581988897471611)

In [31]:
# Find the mean value in each column
np.mean(matrix, axis=0)


array([4., 5., 6.])

1.9 Reshaping Arrays



In [32]:
# Load library
import numpy as np

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [33]:
matrix.size


12

In [34]:
matrix.reshape(1, -1)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [35]:
matrix.reshape(-1, 1)


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [36]:
matrix.reshape(12)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
matrix.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T


array([1, 2, 3, 4, 5, 6])

In [ ]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
matrix.flatten()


In [39]:
matrix.reshape(1, -1)


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

1.12 Finding the Rank of a Matrix



In [40]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)


np.int64(2)

In [41]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]],
                   [[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]]])

# Return matrix rank
np.linalg.matrix_rank(matrix)


array([2, 2])

1.13 Calculating the Determinant



In [42]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)


np.float64(0.0)

1.14 Getting the Diagonal of a Matrix



In [43]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
matrix.diagonal()


array([1, 4, 9])

In [44]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)


array([2, 6])

In [45]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)


array([2, 8])

1.15 Calculating the Trace of a Matrix



In [46]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
matrix.trace()


np.int64(14)

In [47]:
# Return diagonal and sum elements
sum(matrix.diagonal())


np.int64(14)

1.16 Finding Eigenvalues and Eigenvectors



In [48]:
# Load library
import numpy as np
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)

np.int64(32)

1.17 Calculating Dot Products



In [49]:
# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)


np.int64(32)

In [50]:
# Calculate dot product
vector_a @ vector_b


np.int64(32)

1.18 Adding and Subtracting Matrices



In [51]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)


array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [52]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)


array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [53]:
# Add two matrices
matrix_a + matrix_b


array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

1.19 Inverting a Matrix

In [55]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 4],
[2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [56]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

1.20 Generating Random Values

In [57]:
# Load library
import numpy as np
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [59]:
# Generate three random integers between 0 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9], dtype=int32)

In [60]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [61]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [62]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])