# Danial Shater Ghasemi


In [1]:
import tensorflow as tf

In [2]:
tensor_zero_0 = tf.constant(4)
print(tensor_zero_0)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2, 3, -1, 6, -5])

print(tensor_one_d)

tf.Tensor([ 2  3 -1  6 -5], shape=(5,), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2, 3., -1, 6, -5], dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  3. -1.  6. -5.], shape=(5,), dtype=float32)
tf.Tensor([ 2  3 -1  6 -5], shape=(5,), dtype=int16)


In [5]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [6]:
tensor_string = tf.constant(["hello world", " hi"])
print(tensor_string)

tf.Tensor([b'hello world' b' hi'], shape=(2,), dtype=string)


In [7]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1 -2 -3]], shape=(4, 3), dtype=int32)


In [8]:
tensor_three_d = tf.constant([
    [[1,2,3],
    [4,5,6]],

    [[7,8,9],
    [-1,-2,-3]],

    [[2,5,9],
    [-2,6,-3]],
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [-1 -2 -3]]

 [[ 2  5  9]
  [-2  6 -3]]], shape=(3, 2, 3), dtype=int32)


In [9]:
print(tensor_three_d.shape)

(3, 2, 3)


In [10]:
print(tf.shape(tensor_three_d))

tf.Tensor([3 2 3], shape=(3,), dtype=int32)


In [11]:
print(tensor_three_d.ndim)

3


In [12]:
tensor_four_d = tf.constant([
    [[[1,2,3],
    [4,5,6]],

    [[7,8,9],
    [-1,-2,-3]],

    [[2,5,9],
    [-2,6,-3]]],


    [[[10,20,30],
    [40,50,60]],

    [[70,80,90],
    [-10,-20,-30]],

    [[20,50,90],
    [-20,60,-30]]]
])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   3]
   [  4   5   6]]

  [[  7   8   9]
   [ -1  -2  -3]]

  [[  2   5   9]
   [ -2   6  -3]]]


 [[[ 10  20  30]
   [ 40  50  60]]

  [[ 70  80  90]
   [-10 -20 -30]]

  [[ 20  50  90]
   [-20  60 -30]]]], shape=(2, 3, 2, 3), dtype=int32)


In [13]:
import numpy as np

In [14]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [15]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [16]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2, ],
    dtype=tf.dtypes.float32,
    name=None

)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [17]:
filled_tensor = tf.fill([1,3,4], 5)
print(filled_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [18]:
ones_tensor = tf.ones([5,3,2], dtype=tf.dtypes.float32,name=None)

print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [19]:
ones_like_tensor = tf.ones_like(filled_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [20]:
zeros_tensor = tf.zeros([5,3,2], dtype=tf.dtypes.float32,name=None)

print(zeros_tensor)

tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(5, 3, 2), dtype=float32)


In [21]:
t = tf.constant([[1, 1, 1],[2, 2, 2]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [22]:
tf.size(t, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [23]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.93901 100.77268]
 [ 98.06089  99.09366]
 [ 99.7711  100.5763 ]], shape=(3, 2), dtype=float32)


In [24]:
uniform_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=10,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor([9 1 8 3 6], shape=(5,), dtype=int32)


In [25]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [26]:
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 2 2], shape=(3,), dtype=int32)
tf.Tensor([4 2 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 0], shape=(3,), dtype=int32)
tf.Tensor([1 2 1], shape=(3,), dtype=int32)


In [27]:
tensor_indexed = tf.constant([3, 6, 2, 9, 7, 5])

print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6:2])

tf.Tensor([3 6 2 9 7 5], shape=(6,), dtype=int32)
tf.Tensor([3 6 2 9], shape=(4,), dtype=int32)
tf.Tensor([6 9 5], shape=(3,), dtype=int32)


In [28]:
print(tensor_indexed[:4])

tf.Tensor([3 6 2 9], shape=(4,), dtype=int32)


In [29]:
print(tensor_indexed[3:])

tf.Tensor([9 7 5], shape=(3,), dtype=int32)


In [30]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1 -2 -3]], shape=(4, 3), dtype=int32)


In [31]:
print(tensor_two_d[0:3,:])

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [32]:
print(tensor_two_d[...,2])

tf.Tensor([ 3  6  9 -3], shape=(4,), dtype=int32)


In [33]:
tensor_three_d = tf.constant([
    [[1,2,3],
    [4,5,6]],

    [[7,8,9],
    [-1,-2,-3]],

    [[2,5,9],
    [-2,6,-3]],
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [-1 -2 -3]]

 [[ 2  5  9]
  [-2  6 -3]]], shape=(3, 2, 3), dtype=int32)


In [34]:
print(tensor_three_d[0,:,:])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [35]:
print(tensor_three_d[0:2,...,2])

tf.Tensor(
[[ 3  6]
 [ 9 -3]], shape=(2, 2), dtype=int32)


In [36]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [37]:
tf.abs(tf.constant(-5))

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [38]:
x_abs_complex = tf.constant([-2.25 + 3.25j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([3.95284708])>

In [39]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [40]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11], dtype=tf.int32)

print(tf.divide(x_1,x_2))

tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [41]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.float32)
x_2 = tf.constant([7,6,2,6,0,11], dtype=tf.float32)

print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([0.71428573 0.5        3.         1.         0.         0.54545456], shape=(6,), dtype=float32)


In [42]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7], dtype=tf.int32)
x_2_stretched = tf.constant([7,7,7,7,7,7], dtype=tf.int32)

print(tf.add(x_1,x_2))
print(tf.add(x_1,x_2_stretched))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)
tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [43]:
x_1 = tf.constant([[5,3,6,6,4,6],], dtype=tf.int32)
x_2 = tf.constant([[7], [5], [3]], dtype=tf.int32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1,x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35 21 42 42 28 42]
 [25 15 30 30 20 30]
 [15  9 18 18 12 18]], shape=(3, 6), dtype=int32)


In [44]:
x_argmax = tf.constant([[2,20,30,3,6],
                       [3,11,16,1,8],
                       [14,45,23,5,27]])

print(x_argmax.shape)
print(tf.math.argmax(x_argmax, 0))
print(tf.math.argmin(x_argmax, 0))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)


In [45]:
x_argmax = tf.constant([200,120,130,3,6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [46]:
x_argmax = tf.constant([200,120,130,300,6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [47]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
])
print(tensor_two_d)

print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1 -2 -3]], shape=(4, 3), dtype=int32)
tf.Tensor(39, shape=(), dtype=int32)


In [48]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
])
print(tensor_two_d)

print(tf.math.reduce_min(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1 -2 -3]], shape=(4, 3), dtype=int32)
tf.Tensor(-3, shape=(), dtype=int32)


In [49]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
])
print(tensor_two_d.shape)

print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None))

(4, 3)
tf.Tensor([11 13 15], shape=(3,), dtype=int32)


In [50]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
])
print(tensor_two_d.shape)

print(tf.math.reduce_sum(tensor_two_d, axis=1, keepdims=False, name=None))

(4, 3)
tf.Tensor([ 6 15 24 -6], shape=(4,), dtype=int32)


In [51]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
], dtype=tf.float32)
print(tensor_two_d.shape)

print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None))

(4, 3)
tf.Tensor([2.75 3.25 3.75], shape=(3,), dtype=float32)


In [52]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
], dtype=tf.float32)
print(tensor_two_d.shape)

print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=False, name=None))

(4, 3)
tf.Tensor([3.0310888 3.6996622 4.43706  ], shape=(3,), dtype=float32)


In [53]:
tf.math.top_k(tensor_two_d, k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 3.],
       [ 6.],
       [ 9.],
       [-1.]], dtype=float32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2],
       [0]], dtype=int32)>)

In [54]:
x_1 = tf.constant([[1,2,0],
                  [3,5,-1]])
x_2 = tf.constant([[1,2,0],
                  [3,5,-1],
                   [4,5,6]])

print(x_1.shape)
print(x_2.shape)
tf.linalg.matmul(x_1, x_2, transpose_b=False, adjoint_a=False, adjoint_b=False,
                 a_is_sparse=False, b_is_sparse=False, output_type=None, name=None)

(2, 3)
(3, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [55]:
print(x_1@x_2)

tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)


In [56]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [57]:
print(x_1)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [58]:
x_1 = tf.constant([[1,2,0],
                  [3,5,-1]])
x_2 = tf.constant([[1,2,0],
                  [3,5,-1],
                   [4,5,6]])

print(x_1.shape)
print(x_2.shape)
tf.linalg.matmul(x_1, x_2, transpose_b=True, adjoint_a=False, adjoint_b=False,
                 a_is_sparse=False, b_is_sparse=False, output_type=None, name=None)

(2, 3)
(3, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 13, 14],
       [13, 35, 31]], dtype=int32)>

In [59]:
x_1 = tf.constant([
    [[1,2],
    [4,5]],

    [[7,8],
    [-1,-2]],

    [[2,5],
    [-2,6]],
])

x_2 = tf.constant([
    [[1,2,3],
    [4,5,6]],

    [[7,8,9],
    [-1,-2,-3]],

    [[2,5,9],
    [-2,6,-3]],
])


print(x_1.shape)
print(x_2.shape)

print(tf.linalg.matmul(x_1,x_2))

(3, 2, 2)
(3, 2, 3)
tf.Tensor(
[[[  9  12  15]
  [ 24  33  42]]

 [[ 41  40  39]
  [ -5  -4  -3]]

 [[ -6  40   3]
  [-16  26 -36]]], shape=(3, 2, 3), dtype=int32)


In [60]:
x_1=tf.constant([[0,0],
                 [0,2]])

x_2=tf.constant([[1,0,0],
                 [0,0,0]])

print(tf.linalg.matmul(x_1, x_2, a_is_sparse=True, b_is_sparse=True))

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [61]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]],dtype=tf.float16)

tensor_out_d = tf.constant([[1,0,0],
                           [0,5,0],
                           [0,0,6],
                           [0,0,0]], dtype=tf.float16)

tf.linalg.band_part(tensor_two_d, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [62]:
tensor_two_d_m_n = tf.constant([[0,-1,-2],
                                [1,0,-1],
                                [2,1,0],
                                [3,2,1]], dtype=tf.float16)

tensor_two_d_n_m = tf.constant([[0,1,2],
                                [-1,0,1],
                                [-2,-1,0],
                                [-3,-2,-1]], dtype=tf.float16)

In [63]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]],dtype=tf.float32)

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

In [64]:
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  1.6391277e-07],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>

In [65]:
s,v,d = tf.linalg.svd(tensor_two_d)
print(s)
print(v)
print(d)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


# End of 2:30 Video
